# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0212f9eefc68c929d411341987b1b84ecd7240c9de74b94dec990d3ace25c2e270fb19c0b38dafa824376075ef570ba14f49c1da407c64b070af538e76182235

test:
  secret_key_base: fd873ca32097a142d2924638fb384c49016817d391c840a7ea91f8776c1c1d0a72cc6e5d452d579fef958ae32dfb947343439e2aebbfea2c750b7be428de6655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
